const bcrypt = require('bcryptjs');

const hashPassword = async (password) => {
  const salt = await bcrypt.genSalt(10);
  return await bcrypt.hash(password, salt);
};

module.exports = [
  // Citizens (15)
  {
    userId: "USR_CIT_001",
    fullName: "Hanitha Ganisetti",
    role: "citizen",
    aadhaarNumber: "243107701114",
    aadhaarVerified: true,
    panNumber: "ABCDE1234F",
    panVerified: true,
    mobileNumber: "9876543210",
    mobileVerified: true,
    email: "hanitha@example.com",
    dateOfBirth: new Date("1990-05-15"),
    maritalStatus: "Single",
    occupation: "Software Engineer",
    address: {
      street: "123 Main St",
      village: "Madhapur",
      city: "Hyderabad",
      district: "Hyderabad",
      state: "Telangana",
      pincode: "500081"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_002",
    fullName: "Ravi Kumar Sharma",
    role: "citizen",
    aadhaarNumber: "354218812225",
    aadhaarVerified: true,
    panNumber: "FGHIJ5678G",
    panVerified: true,
    mobileNumber: "9876543211",
    mobileVerified: true,
    email: "ravi@example.com",
    dateOfBirth: new Date("1985-08-20"),
    maritalStatus: "Married",
    occupation: "Business Owner",
    address: {
      street: "456 Oak Ave",
      village: "Gachibowli",
      city: "Hyderabad",
      district: "Hyderabad",
      state: "Telangana",
      pincode: "500032"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_003",
    fullName: "Priya Reddy",
    role: "citizen",
    aadhaarNumber: "465329923336",
    aadhaarVerified: true,
    panNumber: "KLMNO9012H",
    panVerified: true,
    mobileNumber: "9876543212",
    mobileVerified: true,
    email: "priya@example.com",
    dateOfBirth: new Date("1992-12-10"),
    maritalStatus: "Married",
    occupation: "Doctor",
    address: {
      street: "789 Pine Rd",
      village: "Jubilee Hills",
      city: "Hyderabad",
      district: "Hyderabad",
      state: "Telangana",
      pincode: "500033"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_004",
    fullName: "Arun Krishnan",
    role: "citizen",
    aadhaarNumber: "576430034447",
    aadhaarVerified: true,
    panNumber: "PQRST3456I",
    panVerified: true,
    mobileNumber: "9876543213",
    mobileVerified: true,
    email: "arun@example.com",
    dateOfBirth: new Date("1988-03-25"),
    maritalStatus: "Single",
    occupation: "Teacher",
    address: {
      street: "101 Maple Dr",
      village: "Vijayawada",
      city: "Vijayawada",
      district: "Krishna",
      state: "Andhra Pradesh",
      pincode: "520001"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_005",
    fullName: "Lakshmi Devi",
    role: "citizen",
    aadhaarNumber: "687541145558",
    aadhaarVerified: true,
    panNumber: "UVWXY7890J",
    panVerified: true,
    mobileNumber: "9876543214",
    mobileVerified: true,
    email: "lakshmi@example.com",
    dateOfBirth: new Date("1980-07-30"),
    maritalStatus: "Widowed",
    occupation: "Retired",
    address: {
      street: "202 Elm St",
      village: "Guntur",
      city: "Guntur",
      district: "Guntur",
      state: "Andhra Pradesh",
      pincode: "522001"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_006",
    fullName: "Suresh Babu",
    role: "citizen",
    aadhaarNumber: "798652256669",
    aadhaarVerified: true,
    panNumber: "ZABCD1234K",
    panVerified: true,
    mobileNumber: "9876543215",
    mobileVerified: true,
    email: "suresh@example.com",
    dateOfBirth: new Date("1975-11-12"),
    maritalStatus: "Married",
    occupation: "Farmer",
    address: {
      street: "303 Cedar Ln",
      village: "Kukatpally",
      city: "Hyderabad",
      district: "Hyderabad",
      state: "Telangana",
      pincode: "500072"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_007",
    fullName: "Anita Kumari",
    role: "citizen",
    aadhaarNumber: "809763367770",
    aadhaarVerified: true,
    panNumber: "EFGHI5678L",
    panVerified: true,
    mobileNumber: "9876543216",
    mobileVerified: true,
    email: "anita@example.com",
    dateOfBirth: new Date("1995-02-18"),
    maritalStatus: "Single",
    occupation: "Accountant",
    address: {
      street: "404 Birch Blvd",
      village: "Secunderabad",
      city: "Secunderabad",
      district: "Medchal",
      state: "Telangana",
      pincode: "500003"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_008",
    fullName: "Venkat Rao",
    role: "citizen",
    aadhaarNumber: "910874478881",
    aadhaarVerified: true,
    panNumber: "MNOPQ9012M",
    panVerified: true,
    mobileNumber: "9876543217",
    mobileVerified: true,
    email: "venkat@example.com",
    dateOfBirth: new Date("1982-09-05"),
    maritalStatus: "Married",
    occupation: "Architect",
    address: {
      street: "505 Spruce Way",
      village: "Tirupati",
      city: "Tirupati",
      district: "Chittoor",
      state: "Andhra Pradesh",
      pincode: "517501"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_009",
    fullName: "Meera Singh",
    role: "citizen",
    aadhaarNumber: "101985589992",
    aadhaarVerified: true,
    panNumber: "RSTUV3456N",
    panVerified: true,
    mobileNumber: "9876543218",
    mobileVerified: true,
    email: "meera@example.com",
    dateOfBirth: new Date("1993-04-22"),
    maritalStatus: "Single",
    occupation: "Lawyer",
    address: {
      street: "606 Willow Pl",
      village: "Nellore",
      city: "Nellore",
      district: "Sri Potti Sri Ramulu Nellore",
      state: "Andhra Pradesh",
      pincode: "524001"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_010",
    fullName: "Rajesh Gupta",
    role: "citizen",
    aadhaarNumber: "212096690003",
    aadhaarVerified: true,
    panNumber: "WXYZA7890O",
    panVerified: true,
    mobileNumber: "9876543219",
    mobileVerified: true,
    email: "rajesh@example.com",
    dateOfBirth: new Date("1987-01-14"),
    maritalStatus: "Married",
    occupation: "Engineer",
    address: {
      street: "707 Ash Ct",
      village: "Warangal",
      city: "Warangal",
      district: "Warangal",
      state: "Telangana",
      pincode: "506001"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_011",
    fullName: "Sunita Patel",
    role: "citizen",
    aadhaarNumber: "323107701114",
    aadhaarVerified: true,
    panNumber: "BCDEF1234P",
    panVerified: true,
    mobileNumber: "9876543220",
    mobileVerified: true,
    email: "sunita@example.com",
    dateOfBirth: new Date("1991-06-30"),
    maritalStatus: "Married",
    occupation: "Designer",
    address: {
      street: "808 Poplar Ave",
      village: "Karimnagar",
      city: "Karimnagar",
      district: "Karimnagar",
      state: "Telangana",
      pincode: "505001"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_012",
    fullName: "Kiran Kumar",
    role: "citizen",
    aadhaarNumber: "434218812225",
    aadhaarVerified: true,
    panNumber: "GHIJK5678Q",
    panVerified: true,
    mobileNumber: "9876543221",
    mobileVerified: true,
    email: "kiran@example.com",
    dateOfBirth: new Date("1989-10-08"),
    maritalStatus: "Single",
    occupation: "Consultant",
    address: {
      street: "909 Fir St",
      village: "Khammam",
      city: "Khammam",
      district: "Khammam",
      state: "Telangana",
      pincode: "507001"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_013",
    fullName: "Deepa Nair",
    role: "citizen",
    aadhaarNumber: "545329923336",
    aadhaarVerified: true,
    panNumber: "LMNOP9012R",
    panVerified: true,
    mobileNumber: "9876543222",
    mobileVerified: true,
    email: "deepa@example.com",
    dateOfBirth: new Date("1984-12-17"),
    maritalStatus: "Married",
    occupation: "Manager",
    address: {
      street: "1010 Cypress Rd",
      village: "Rajahmundry",
      city: "Rajahmundry",
      district: "East Godavari",
      state: "Andhra Pradesh",
      pincode: "533101"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_014",
    fullName: "Ramesh Choudhary",
    role: "citizen",
    aadhaarNumber: "656430034447",
    aadhaarVerified: true,
    panNumber: "QRSTU3456S",
    panVerified: true,
    mobileNumber: "9876543223",
    mobileVerified: true,
    email: "ramesh@example.com",
    dateOfBirth: new Date("1978-03-03"),
    maritalStatus: "Married",
    occupation: "Contractor",
    address: {
      street: "1111 Redwood Ln",
      village: "Anantapur",
      city: "Anantapur",
      district: "Anantapur",
      state: "Andhra Pradesh",
      pincode: "515001"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },
  {
    userId: "USR_CIT_015",
    fullName: "Kavitha Reddy",
    role: "citizen",
    aadhaarNumber: "767541145558",
    aadhaarVerified: true,
    panNumber: "VWXYZ7890T",
    panVerified: true,
    mobileNumber: "9876543224",
    mobileVerified: true,
    email: "kavitha@example.com",
    dateOfBirth: new Date("1994-07-25"),
    maritalStatus: "Single",
    occupation: "Writer",
    address: {
      street: "1212 Sequoia Pl",
      village: "Kurnool",
      city: "Kurnool",
      district: "Kurnool",
      state: "Andhra Pradesh",
      pincode: "518001"
    },
    password: hashPassword("Test@1234"),
    kycCompleted: true,
    isActive: true
  },

  // Officers (6)
  {
    userId: "USR_OFF_001",
    fullName: "Revenue Officer 1",
    role: "revenue_officer",
    employeeId: "REV001",
    department: "Revenue Department",
    designation: "Officer",
    email: "revenue1@land.gov.in",
    password: hashPassword("Rev@123"),
    isActive: true
  },
  {
    userId: "USR_OFF_002",
    fullName: "Revenue Officer 2",
    role: "revenue_officer",
    employeeId: "REV002",
    department: "Revenue Department",
    designation: "Officer",
    email: "revenue2@land.gov.in",
    password: hashPassword("Rev@123"),
    isActive: true
  },
  {
    userId: "USR_OFF_003",
    fullName: "SBI Bank Manager",
    role: "bank_manager",
    employeeId: "SBI001",
    department: "Bank",
    designation: "Manager",
    bankId: "BANK_SBI",
    email: "sbimanager@bank.com",
    password: hashPassword("Bank@123"),
    isActive: true
  },
  {
    userId: "USR_OFF_004",
    fullName: "HDFC Bank Manager",
    role: "bank_manager",
    employeeId: "HDFC001",
    department: "Bank",
    designation: "Manager",
    bankId: "BANK_HDFC",
    email: "hdfcmanager@bank.com",
    password: hashPassword("Bank@123"),
    isActive: true
  },
  {
    userId: "USR_OFF_005",
    fullName: "Sub-Registrar",
    role: "sub_registrar",
    employeeId: "REG001",
    department: "Registration Department",
    designation: "Officer",
    email: "registrar@land.gov.in",
    password: hashPassword("Reg@123"),
    isActive: true
  },
  {
    userId: "USR_OFF_006",
    fullName: "System Admin",
    role: "admin",
    employeeId: "ADMIN001",
    department: "IT Department",
    designation: "Administrator",
    email: "admin@land.gov.in",
    password: hashPassword("Admin@123"),
    isActive: true
  }
];